### ISSUE TITLE
Add annotation for optional attributes in EXPRESS

### ISSUE THREAD

**Issue by riemi-nie** [Bitub/step#22]
Add an annotation to all attributes in the Xcore model which are declared optional in the EXPRESS based schema instance.

Expected result could be:

`@Optional`
or
`@XcoreModel(optional="true")`

The value is that for the purpose of deriving a MVD from the hole schema of IFC, the information of possible optional attributes is embedded in the model.

**Comment by bekraft** [comment]
Added annotation with default "false" as unmentioned annotation in model
